[package]
name = "docx2pdf_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
zip = "0.6"
quick-xml = "0.36"
anyhow = "1"
pdf-writer = "0.14.0"
image = "0.25.8"
tempfile = "3.23.0"
rayon = "1.11.0"
uuid = "1.18.1"
turbojpeg = "1.3.3"

stats_alloc = "0.1"
